<?php
$title = 'Edit article';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/article', ['action' => 'edit', 'id' => $this->id]));
$form->prepare();

?>
<?= $this->partial('partial/titleAndBreadcrumbTemplate', ['title' => $title]) ?>
<div class="row">
    <div class="col-sm-8">
        <?= $this->form()->openTag($form) ?>
        <?php
        foreach ($form as $element) {
            $label = '';
            $formElement = '';
            $attributes = $element->getAttributes();

            if ($element->getLabel()) {
                if (isset($attributes['required']) && $attributes['required'] == 'required') {
                    $element->setLabel($element->getLabel() . ' *');
                }

                $label = $this->formLabel($element);
                $label = str_replace('*', '<strong class="asterisk">*</strong>', $label);
            }

            if (isset($attributes['type'])) {
                switch ($attributes['type']) {
                    case 'text':
                        $formElement .= '<div class="col-sm-10">';
                        $formElement .= $this->formText($element);
                        $formElement .= $this->formElementErrors($element);
                        $formElement .= '</div>';
                        break;
                    case 'textarea':
                        $formElement .= '<div class="col-sm-10">';
                        $formElement .= $this->formTextarea($element);
                        $formElement .= $this->formElementErrors($element);
                        $formElement .= '</div>';
                        break;
                    case 'file':
                        $formElement .= '<div class="col-sm-10">';
                        $formElement .= $this->formFile($element);
                        $formElement .= $this->formElementErrors($element);
                        $formElement .= '<p><img src="' . $this->article->getImage() .'" width="100" height="80"></p>';
                        $formElement .= '</div>';
                        break;
                    case 'checkbox':
                        $formElement .= '<div class="col-sm-10">';
                        $formElement .= $this->formCheckbox($element);
                        $formElement .= $this->formElementErrors($element);
                        $formElement .= '</div>';
                        break;
                    case 'select':
                        $formElement .= '<div class="col-sm-10">';
                        $formElement .= $this->formSelect($element);
                        $formElement .= $this->formElementErrors($element);
                        $formElement .= '</div>';
                        break;
                    case 'submit':
                        $formElement .= '<div class="col-sm-12 col-sm-offset-2">';
                        $formElement .= $this->formSubmit($element);
                        $formElement .= '</div>';
                        break;
                }
            }

            echo '<div class="form-group">' . $label . $formElement . '</div>';
        }
        ?>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
