<?php
$title = 'Manage articles';
$this->headTitle($title);
?>
<?= $this->partial('partial/titleAndBreadcrumbTemplate', ['title' => $title]) ?>
<div class="row">
    <div class="col-sm-12">
        <div>
            <a href="<?= $this->url('admin/article', ['action' => 'add']) ?>" class="btn btn-default">Add article</a>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-12">
        <h4>Articles list</h4>
    </div>
</div>

