<?php
$this->headScript()->appendScript("$(function(){ $('ul.nav.navbar-nav li').eq(0).addClass('active'); });");

$title = 'Sample';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $title ?></h3>
    </div>
</div>
<?php
echo $this->flashMessenger()->render('success', ['success-class']);
echo $this->flashMessenger()->render('error',   ['error-class']);
?>
<div><?= $this->escapeHtml($this->greeting) ?></div>
<p><?= $this->escapeHtml($this->url) ?></p>
<p><?= $this->escapeHtml($this->date) ?></p>
<p><?= $this->getTime() ?></p>
<p><a href="/tutorial/sample/example">Example</a></p>
<p class="error-class"><?= $this->escapeHtml($this->message) ?></p>
<form action="/tutorial/sample/foo" method="post">
    <input type="text" name="title">
    <button>Submit</button>
</form>
<p><a href="/tutorial/sample/download">Download</a></p>
