<?php
if ($this->category) {
    $title = $this->escapeHtml($this->category->getName());
    $this->headTitle($title);
}
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $title ?></h3>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-3">
        <div><?= $this->getCategory() ?></div>
    </div>
    <div class="col-sm-9">
        <?php if (! $this->articles) : ?>
            <h4>List is empty</h4>
        <?php else : ?>
            <?php foreach ($this->articles as $article) : ?>
                <div class="panel">
                    <div class="panel-heading">
                        <h4><?= $this->escapeHtml($article->getTitle()) ?></h4>
                        <br>
                        <div class="overflow-hidden">
                            <img src="<?= $this->escapeHtml($article->getImage()) ?>"
                                 class="img-responsive pull-left app-img"
                                 width="100"
                                 height="60"
                                 src="image"
                            >
                            <div><?= $this->escapeHtml($article->getShortContent()) ?></div>
                        </div>
                    </div>
                    <br>
                    <div class="panel-footer">
                        <a href="/blog/article/<?= (int)$article->getId() ?>">Read More &raquo;</a>
                    </div>
                </div>
                <br>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
