<?php
$title = 'Add category';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/category', ['action' => 'add']));
$form->prepare();
?>
<?= $this->partial('partial/titleAndBreadcrumbTemplate', ['title' => $title]) ?>
<br>
<div class="row">
    <div class="col-sm-6">
        <?= $this->form()->openTag($form) ?>
        <?= $this->formHidden($form->get('hidden')) ?>
        <div class="form-group">
            <div class="col-sm-2">
                <?= $this->formLabel($form->get('name')) ?>
            </div>
            <div class="col-sm-10">
                <?= $this->formText($form->get('name')) ?>
                <?= $this->formElementErrors($form->get('name')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2">
                <?= $this->formLabel($form->get('parent')) ?>
            </div>
            <div class="col-sm-10">
                <?= $this->formSelect($form->get('parent')) ?>
                <?= $this->formElementErrors($form->get('parent')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2">
                <?= $this->formLabel($form->get('isPublic')) ?>
            </div>
            <div class="col-sm-10">
                <?= $this->formCheckbox($form->get('isPublic')) ?>
                <?= $this->formElementErrors($form->get('isPublic')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-sm-offset-2">
                <?= $this->formSubmit($form->get('submit')) ?>
            </div>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
