<?php
$title = 'Manage categories';
$this->headTitle($title);
?>
<?= $this->partial('partial/titleAndBreadcrumbTemplate', ['title' => $title]) ?>
<div class="row">
    <div class="col-sm-6">
        <div>
            <a href="<?= $this->url('admin/category', ['action' => 'add']) ?>" class="btn btn-default">Add category</a>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="text-right pull-right flash-message">
            <?= $this->flashMessenger()->render('success', ['success-message']); ?>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-sm-12">
        <?php if (! $this->categories) : ?>
        <h4>List is empty</h4>
        <?php else : ?>
        <h4>Categories list</h4>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Parent</th>
                    <th>Name</th>
                    <th>Is visible</th>
                    <th>Actions</th>
                </tr>
                <?php foreach ($this->categories as $category) : ?>
                <tr>
                    <td><?= $this->escapeHtml($category->getId()) ?></td>
                    <td><?= $this->escapeHtml($this->getParentCategoryName($this->categories, $category)) ?></td>
                    <td><?= $this->escapeHtml($category->getName()) ?></td>
                    <td><?= $this->escapeHtml($category->getIsPublic()) ? 'Yes' : 'No'; ?></td>
                    <td>
                        <a href="<?= $this->url('admin/category', ['action' => 'edit', 'id' => (int)$category->getId()]) ?>">
                            Edit
                        </a>
                        &nbsp;&nbsp;|&nbsp;&nbsp;
                        <?php
                        $form = $this->form;
                        $form->setAttributes([
                            'action' => $this->url('admin/category', ['action' => 'delete', 'id' => (int)$category->getId()]),
                            'class' => 'form-delete confirm-plugin',
                        ]);
                        $form->prepare();

                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('csrf'));
                        /* Here jquery script(j-confirm-action.js) did not work with name 'submit' */
                        echo $this->formSubmit($form->get('submit')->setValue('Delete')->setAttribute('name', 'send')->removeAttribute('class', 'btn btn-default'));
                        echo $this->form()->closeTag();
                        ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <?php endif; ?>
    </div>
</div>
