<?php

$value = 10.2;

$floatValidator = new \Application\Validator\FloatValidator();

if ($floatValidator->isValid($value)) {
    echo 'OK';
} else {
    foreach ($floatValidator->getMessages() as $message) {
        echo '<div>' . $message . '</div>';
    }
}





$title = 'Blog';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $title ?></h3>
    </div>
</div>
<form action="/blog" method="post">
    <input type="text" name="title">
    <button>Submit</button>
</form>
